#!/usr/bin/env node

/**
 * Custom ui-grid build script.
 *
 * Generates a grid build with only selected features and/or a custom locale
 * baked in. Produces the smallest possible JS binary by letting the bundler
 * tree-shake code guarded by disabled feature flags.
 *
 * Usage:
 *   node scripts/build-grid.mjs                                  # full build, en-US
 *   node scripts/build-grid.mjs --features sorting,filtering      # minimal build
 *   node scripts/build-grid.mjs --locale i18n/fr-FR.json          # French labels
 *   node scripts/build-grid.mjs --features sorting --locale i18n/fr-FR.json
 *   node scripts/build-grid.mjs --list                            # list available features
 *
 * Options:
 *   --features <list>   Comma-separated features to enable. Default: all.
 *   --locale   <path>   Path to a JSON locale file to bake in as defaults.
 *   --list              Print all available feature flags and exit.
 *   --dry-run           Write the generated files but skip the ng build step.
 */

import { existsSync, readFileSync, writeFileSync, copyFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { execSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

const FEATURES_PATH = resolve(ROOT, 'projects/ui-grid/src/lib/grid/grid.features.ts');
const LABELS_PATH = resolve(ROOT, 'projects/ui-grid/src/lib/grid/i18n/en-US.json');
const FEATURES_BACKUP = FEATURES_PATH + '.bak';
const LABELS_BACKUP = LABELS_PATH + '.bak';

const ALL_FEATURES = [
  'sorting',
  'filtering',
  'grouping',
  'pagination',
  'cell-edit',
  'expandable',
  'tree-view',
  'infinite-scroll',
  'column-moving',
  'csv-export',
  'save-state',
  'auto-resize',
];

/** Map CLI feature name → TypeScript const name */
function toConstName(feature) {
  return 'FEATURE_' + feature.toUpperCase().replace(/-/g, '_');
}

function parseArgs(argv) {
  const args = { features: null, locale: null, list: false, dryRun: false };
  for (let i = 2; i < argv.length; i++) {
    switch (argv[i]) {
      case '--features':
        args.features = argv[++i]?.split(',').map((f) => f.trim().toLowerCase()) ?? [];
        break;
      case '--locale':
        args.locale = argv[++i];
        break;
      case '--list':
        args.list = true;
        break;
      case '--dry-run':
        args.dryRun = true;
        break;
      default:
        console.error(`Unknown option: ${argv[i]}`);
        process.exit(1);
    }
  }
  return args;
}

function generateFeaturesFile(enabledFeatures) {
  const lines = [
    '/**',
    ' * Auto-generated by scripts/build-grid.mjs',
    ` * Enabled features: ${enabledFeatures.join(', ') || 'none'}`,
    ' */',
  ];

  for (const feature of ALL_FEATURES) {
    const enabled = enabledFeatures.includes(feature);
    lines.push(`export const ${toConstName(feature)} = ${enabled};`);
  }

  return lines.join('\n') + '\n';
}

function validateFeatures(features) {
  const invalid = features.filter((f) => !ALL_FEATURES.includes(f));
  if (invalid.length > 0) {
    console.error(`Unknown feature(s): ${invalid.join(', ')}`);
    console.error(`Available: ${ALL_FEATURES.join(', ')}`);
    process.exit(1);
  }
}

function validateLocale(localePath) {
  const resolved = resolve(ROOT, localePath);
  if (!existsSync(resolved)) {
    console.error(`Locale file not found: ${resolved}`);
    process.exit(1);
  }
  // Validate JSON structure
  try {
    JSON.parse(readFileSync(resolved, 'utf-8'));
  } catch {
    console.error(`Invalid JSON in locale file: ${resolved}`);
    process.exit(1);
  }
  return resolved;
}

function main() {
  const args = parseArgs(process.argv);

  if (args.list) {
    console.log('Available feature flags:\n');
    for (const feature of ALL_FEATURES) {
      console.log(`  ${feature.padEnd(20)} ${toConstName(feature)}`);
    }
    console.log(`\nDefault: all enabled`);
    process.exit(0);
  }

  const enabledFeatures = args.features ?? [...ALL_FEATURES];
  validateFeatures(enabledFeatures);

  const resolvedLocale = args.locale ? validateLocale(args.locale) : null;

  console.log('┌─────────────────────────────────────────┐');
  console.log('│  ui-grid custom build                   │');
  console.log('├─────────────────────────────────────────┤');
  console.log(`│  Features: ${enabledFeatures.length}/${ALL_FEATURES.length} enabled`);
  if (resolvedLocale) {
    console.log(`│  Locale:   ${args.locale}`);
  }
  console.log('└─────────────────────────────────────────┘');
  console.log();

  // Backup originals
  copyFileSync(FEATURES_PATH, FEATURES_BACKUP);
  if (resolvedLocale) {
    copyFileSync(LABELS_PATH, LABELS_BACKUP);
  }

  let exitCode = 0;

  try {
    // Write custom features file
    const featuresContent = generateFeaturesFile(enabledFeatures);
    writeFileSync(FEATURES_PATH, featuresContent, 'utf-8');
    console.log(`✓ Wrote ${FEATURES_PATH}`);

    for (const feature of ALL_FEATURES) {
      const enabled = enabledFeatures.includes(feature);
      console.log(`  ${enabled ? '●' : '○'} ${toConstName(feature)} = ${enabled}`);
    }
    console.log();

    // Write custom locale
    if (resolvedLocale) {
      copyFileSync(resolvedLocale, LABELS_PATH);
      console.log(`✓ Copied locale ${args.locale} → i18n/en-US.json`);
      console.log();
    }

    if (args.dryRun) {
      console.log('⏭  Dry run — skipping ng build');
    } else {
      console.log('Building library...\n');
      execSync('npx ng build uiGridPackage --configuration production', {
        cwd: ROOT,
        stdio: 'inherit',
      });
      console.log('\n✓ Build complete');
    }
  } catch (err) {
    console.error('\n✗ Build failed:', err.message);
    exitCode = 1;
  } finally {
    // Restore originals
    copyFileSync(FEATURES_BACKUP, FEATURES_PATH);
    writeFileSync(FEATURES_BACKUP, '', 'utf-8');
    console.log('✓ Restored grid.features.ts');

    if (resolvedLocale) {
      copyFileSync(LABELS_BACKUP, LABELS_PATH);
      writeFileSync(LABELS_BACKUP, '', 'utf-8');
      console.log('✓ Restored i18n/en-US.json');
    }
  }

  process.exit(exitCode);
}

main();
